#!/usr/bin/env bash
# script that configures a comntaineir.
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /usr/share/nginx
chmod 0644 /etc/nginx/nginx.conf
su nginx -c nginx
